---
- beta
  - version: 90.*
    blobs:
    - reset-search-defaults@mozilla.com-2.0.0-3
  - version: 86.*
    blobs:
    - reset-search-defaults@mozilla.com-1.0.3
  - version: 60.*
    blobs:
    - tls13-version-fallback-rollout-bug1448176@mozilla.org-2.0
  - version: 58.*
    blobs:
    - disable-js-shared-memory@mozilla.org-2.0
  - version: 54.*
    blobs:
    - Shield-recipe-client-1.0.0
  - version: 52.*
    blobs:
    - Diagnostics-1.0
  - version: 47.*
    blobs:
    - Pocket-ff47-1.0
    - Loop-1.3.2
    - E10srollout-ff47-1.0
    comment: Hello offers to 47beta
